### ISSUE TITLE
QQ Still active?

### ISSUE THREAD

**Issue by pblankley** [frenchtoast747/granite#1]
Hey Aaron! 

Is this project still active / used by you? 

If it's not, I was wondering if I could use the `granite` name on pypi.

Thanks for taking the time to read this and let me know! 

Thanks,
Paul

**Comment by frenchtoast747** [comment]
Hey Paul, I _do_ still use this package quite a bit for work-related and personal projects. I will admit that it's not a large project and it hasn't seen any new features in a while (I really haven't needed any), but based on the statistics of downloads, I wouldn't say it's dead either: https://pypistats.org/packages/granite

Thanks for reaching out!

**Comment by pblankley** [comment]
Thanks for the quick response!
